# Generated by Django 4.2.5 on 2023-09-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controleTarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinasentidade',
            old_name='descrição',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefasentidade',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
